interface CompanyData {
  id: string;
  companyname: string;
  sector: string | null;
  scope1: number | null;
  scope2: number | null;
  scope3: number | null;
  totaloutput_along_with_unit: string;
  is_msme: boolean;
  link_to_image: string | null;
}

const data: CompanyData[] = [
  {
    id: "A1B2C3",
    companyname: "ABC Company",
    sector: "Manufacturing",
    scope1: 10.5,
    scope2: 20.3,
    scope3: 15.7,
    totaloutput_along_with_unit: "5000 kg",
    is_msme: true,
    link_to_image: "https://s3.bucket/image1.jpg",
  },
  {
    id: "Z1A2B3",
    companyname: "Innovative Solutions",
    sector: null,
    scope1: 12.4,
    scope2: 22.1,
    scope3: 17.5,
    totaloutput_along_with_unit: "80 kg",
    is_msme: true,
    link_to_image: "https://s3.bucket/image1.jpg",
  },
  {
    id: "C4D5E6",
    companyname: "Eco-Friendly Tech",
    sector: "Environmental",
    scope1: null,
    scope2: 19.8,
    scope3: 14.3,
    totaloutput_along_with_unit: "45 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image18.jpg",
  },
  {
    id: "F7G8H9",
    companyname: "FinTech Disruptors",
    sector: "Financial Services",
    scope1: 10.2,
    scope2: null,
    scope3: 15.9,
    totaloutput_along_with_unit: "5500 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image19.jpg",
  },
  {
    id: "I1J2K3",
    companyname: "BioTech Innovations",
    sector: "Biotechnology",
    scope1: 13.8,
    scope2: 23.7,
    scope3: null,
    totaloutput_along_with_unit: "120 vehicles",
    is_msme: false,
    link_to_image: "https://s3.bucket/image20.jpg",
  },
  {
    id: "L4M5N6",
    companyname: "Sustainable Solutions",
    sector: "Waste Management",
    scope1: null,
    scope2: 20.9,
    scope3: 16.2,
    totaloutput_along_with_unit: "55 tons",
    is_msme: true,
    link_to_image: "https://s3.bucket/image21.jpg",
  },
  {
    id: "O7P8Q9",
    companyname: "HealthTech Innovators",
    sector: "Healthcare",
    scope1: 11.6,
    scope2: 21.4,
    scope3: 17.3,
    totaloutput_along_with_unit: "7200 litres",
    is_msme: false,
    link_to_image: "https://s3.bucket/image21.jpg",
  },
  {
    id: "R1S2T3",
    companyname: "Agri-Tech Solutions",
    sector: "Agriculture",
    scope1: 9.4,
    scope2: null,
    scope3: 13.9,
    totaloutput_along_with_unit: "85 vehicles",
    is_msme: true,
    link_to_image: "https://s3.bucket/image22.jpg",
  },
  {
    id: "U4V5W6",
    companyname: "Logistics Innovators",
    sector: "Transportation",
    scope1: 12.9,
    scope2: 22.5,
    scope3: null,
    totaloutput_along_with_unit: "65 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image23.jpg",
  },
  {
    id: "X7Y8Z9",
    companyname: "FinTech Disruptors",
    sector: "Financial Services",
    scope1: null,
    scope2: 19.7,
    scope3: 15.4,
    totaloutput_along_with_unit: "5800 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image24.jpg",
  },
  {
    id: "A1B2C3",
    companyname: "CleanTech Solutions",
    sector: "Renewable Energy",
    scope1: 13.5,
    scope2: 23.3,
    scope3: 18.8,
    totaloutput_along_with_unit: "75 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image1.jpg",
  },
  {
    id: "D4E5F6",
    companyname: "XYZ Corporation",
    sector: "Technology",
    scope1: 8.2,
    scope2: 18.9,
    scope3: 12.4,
    totaloutput_along_with_unit: "100 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image2.jpg",
  },
  {
    id: "G7H8I9",
    companyname: "123 Industries",
    sector: "Energy",
    scope1: 15.6,
    scope2: 25.1,
    scope3: 18.3,
    totaloutput_along_with_unit: "7500 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image3.jpg",
  },
  {
    id: "abc123",
    companyname: "Company A",
    sector: "Manufacturing",
    scope1: 100,
    scope2: 200,
    scope3: 150,
    totaloutput_along_with_unit: "500 kg",
    is_msme: true,
    link_to_image: "https://s3.bucket.com/images/company_a.jpg",
  },
  {
    id: "def456",
    companyname: "Company B",
    sector: "Technology",
    scope1: 50,
    scope2: 100,
    scope3: 75,
    totaloutput_along_with_unit: "250 litres",
    is_msme: false,
    link_to_image: "https://s3.bucket.com/images/company_b.jpg",
  },
  {
    id: "ghi789",
    companyname: "Company C",
    sector: "Transportation",
    scope1: 200,
    scope2: 400,
    scope3: 300,
    totaloutput_along_with_unit: "1000 tons",
    is_msme: true,
    link_to_image: "https://s3.bucket.com/images/company_c.jpg",
  },
  {
    id: "J1K2L3",
    companyname: "Tech Innovators Ltd",
    sector: "Information Technology",
    scope1: 12.8,
    scope2: 22.7,
    scope3: 17.2,
    totaloutput_along_with_unit: "12000 kg",
    is_msme: false,
    link_to_image: "https://s3.bucket/image4.jpg",
  },
  {
    id: "M4N5O6",
    companyname: "Green Solutions Inc",
    sector: "Environmental Services",
    scope1: 9.3,
    scope2: 19.6,
    scope3: 14.5,
    totaloutput_along_with_unit: "50 tons",
    is_msme: true,
    link_to_image: "https://s3.bucket/image5.jpg",
  },
  {
    id: "P7Q8R9",
    companyname: "FoodTech Enterprises",
    sector: "Food & Beverage",
    scope1: 14.2,
    scope2: 24.5,
    scope3: 20.1,
    totaloutput_along_with_unit: "10000 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image6.jpg",
  },
  {
    id: "S1T2U3",
    companyname: "InnoTech Solutions",
    sector: "Consulting",
    scope1: 11.5,
    scope2: 21.3,
    scope3: 16.8,
    totaloutput_along_with_unit: "200 vehicles",
    is_msme: false,
    link_to_image: "https://s3.bucket/image7.jpg",
  },
  {
    id: "V4W5X6",
    companyname: "Eco-Friendly Enterprises",
    sector: "Renewable Energy",
    scope1: 13.7,
    scope2: 23.4,
    scope3: 18.9,
    totaloutput_along_with_unit: "80 tons",
    is_msme: true,
    link_to_image: "https://s3.bucket/image8.jpg",
  },
  {
    id: "Y7Z8A9",
    companyname: "FinTech Solutions",
    sector: "Financial Services",
    scope1: 10.1,
    scope2: 20.8,
    scope3: 15.3,
    totaloutput_along_with_unit: "5000 litres",
    is_msme: false,
    link_to_image: "https://s3.bucket/image9.jpg",
  },
  {
    id: "B1C2D3",
    companyname: "BioTech Innovations",
    sector: "Biotechnology",
    scope1: 14.9,
    scope2: 24.2,
    scope3: 19.6,
    totaloutput_along_with_unit: "150 vehicles",
    is_msme: true,
    link_to_image: "https://s3.bucket/image10.jpg",
  },
  {
    id: "E4F5G6",
    companyname: "Sustainable Solutions",
    sector: "Waste Management",
    scope1: 11.3,
    scope2: 21.6,
    scope3: 16.4,
    totaloutput_along_with_unit: "60 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image11.jpg",
  },
  {
    id: "H7I8J9",
    companyname: "HealthTech Innovators",
    sector: "Healthcare",
    scope1: 12.5,
    scope2: 22.9,
    scope3: 17.8,
    totaloutput_along_with_unit: "8000 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image12.jpg",
  },
  {
    id: "K1L2M3",
    companyname: "Agri-Tech Solutions",
    sector: "Agriculture",
    scope1: 9.7,
    scope2: 19.3,
    scope3: 14.1,
    totaloutput_along_with_unit: "100 vehicles",
    is_msme: true,
    link_to_image: "https://s3.bucket/image13.jpg",
  },
  {
    id: "N4O5P6",
    companyname: "Logistics Innovators",
    sector: "Transportation",
    scope1: 13.2,
    scope2: 23.8,
    scope3: 18.5,
    totaloutput_along_with_unit: "70 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image14.jpg",
  },
  {
    id: "Q7R8S9",
    companyname: "FinTech Disruptors",
    sector: "Financial Services",
    scope1: 10.9,
    scope2: 20.4,
    scope3: 15.7,
    totaloutput_along_with_unit: "6000 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image15.jpg",
  },
  {
    id: "T1U2V3",
    companyname: "CleanTech Solutions",
    sector: "Renewable Energy",
    scope1: 14.3,
    scope2: 24.6,
    scope3: 19.2,
    totaloutput_along_with_unit: "90 tons",
    is_msme: false,
    link_to_image: "https://s3.bucket/image16.jpg",
  },
  {
    id: "W4X5Y6",
    companyname: "HealthCare Innovators",
    sector: "Healthcare",
    scope1: 11.7,
    scope2: 21.2,
    scope3: 16.1,
    totaloutput_along_with_unit: "7500 litres",
    is_msme: true,
    link_to_image: "https://s3.bucket/image17.jpg",
  },
];

export default data;
